project:
  type: website
  output-dir: docs

website:
  title: "Data Exploration"
  favicon: images/magnifying.png
  google-analytics: G-0G1PHPKVFB
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - materials.qmd
      - labs.qmd
      - discord.qmd
      - grades.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



