---
title: "Materials"
---

**Welcome**

- Week One: January 14, 16: Setup
  - Reading: [Making Sense of Data, Chapter 2, p. 19-32](https://ebookcentral.proquest.com/lib/allegheny-ebooks/reader.action?docID=427614&ppg=35)
  - Slides: [Welcome Reveal](slides/01-welcome.qmd), [Welcome PDF](slides/01-welcome.pdf)
  - Lab: [Practice Lab](https://classroom.github.com/a/ypH8iEXF) Due: Thursday Jan 23, 2:30pm

**Data Display**

- Week Two: January 21, 23: Display Types and Anatomy of a Chart
  - Reading: [Making Sense of Data, Chapter 2, p. 32-50](https://ebookcentral.proquest.com/lib/allegheny-ebooks/reader.action?docID=427614&ppg=48)
  - Slides: Display Types and Anatomy of a Chart [Reveal](slides/02-data-display.qmd), [PDF](slides/02-data-display.pdf)
  - Class Activity: [Data Display](code/data_display_activity.ipynb)
  - Lab: [Data Display](https://classroom.github.com/a/4qDGRQsy) Due: Thursday Jan 30, 2:30pm
- Week Three: January 28, 30: Data Distortion
  - Reading: [Misleading Graphs](https://web.stevenson.edu/mbranson/m4tp/version1/fake-news-misleading-graphs.html)
  - Class Activity: [Data Distortion](code/data_distortion_activity.ipynb)
  - Lab: [Data Distortion](https://classroom.github.com/a/MlNXvWRF) Due: Thursday Feb 6, 2:30pm
- Week Four: February 4, 7: Data Filtering
  - Video: [Logical Indexing](https://youtu.be/v5pJfu-yn-0)
  - Class Activity: [Data Filtering](code/data_filtering_activity.ipynb)
  - Lab: [Data Filtering](https://classroom.github.com/a/TwR2gnVy) Due: Thursday Feb 13, 2:30pm 
  - [Activities Repo](https://classroom.github.com/a/WsxZrwZP) 
- Week Five: February 11, 13: Interactive Display
  - Explore: [Interactive Viz Gallery](https://www.tableau.com/viz-gallery)
  - Class Activity: [Data Interactivity](code/data_interactivity_activity.ipynb)
  - Lab: [Data Interactivity](https://classroom.github.com/a/xwNOik6D) Due: Thursday Feb 20, 2:30pm
  
**Data Gathering**

- Week Six: February 18, 20: Turning Anything Into Data
  - Reading: [Variable Types](https://www150.statcan.gc.ca/n1/edu/power-pouvoir/ch8/5214817-eng.htm)
  - Slides: [Data Gathering](slides/06-data-gathering.qmd)
  - Class Activity: [Google Form Data](https://forms.gle/rqqcmMtnEHc6g3276)
  - Class Activity: [Make data-gathering-activity.csv](slides/06-data-gathering.qmd#csv-activity)
  - Lab: [Data Entry](https://classroom.github.com/a/ltosB-79) Due: Thursday Feb 27, 2:30pm
- Week Seven: February 25, 27: Web Data Analytics and Scraping
  - Reading: [Site Maps](https://markitors.com/what-is-a-sitemap/)
  - Slides: [Gathering Web Data](slides/07-web-data.qmd)
  - Class Activity Optional: [Make data-scraping-activity.csv](slides/07-web-data.qmd#optional-activity)
  - Lab: [Data Analytics](https://classroom.github.com/a/PjJ1a7Oy) Due Thursday March 13, 2:30pm
  <!-- https://quarto.org/docs/publishing/ci.html -->
  <!-- https://allegheny.edu/sitemap_index.xml -->
- Spring Break: March 1-9
- Week Nine: March 11, 13: Data Wrangling
  <!-- - Reading: [Site Maps](https://markitors.com/what-is-a-sitemap/) -->
  <!-- - Slides: [Data Wrangling](slides/09-data-wrangling.qmd) -->
  - Class Activity: [Data Wrangling Notebook](code/data_wrangling_activity.ipynb)
  - Lab: [Data Wrangling](https://classroom.github.com/a/su5FvGaJ) Due Thursday, March 27, 2:30pm


**Data Processing**

- Week Ten: March 18, 20: Statistics
  - Class Activity: [Stats Intro Notebook](code/stats_intro_activity.ipynb)
  <!-- - Lab: Numpy Calculations -->
- Week Eleven: March 25, 27: Data Transformations
  - Lab: Dot-to-dot
- Week Twelve: April 1, 3: Modeling and Overfitting
  - Lab: Matplotlib
- Week Thirteen: April 8: Clustering
  <!-- https://youtu.be/9Mmj8NMCqEQ  -->

**Data Storytelling**

- Week Fourteen: April 15, 17: Hypothesis Driven Analysis
  - Lab: Hypothesis Testing
- Week Fifteen: April 22, 24: Storytelling Challenge & Project Preparation
- Week Sixteen: April 29: No Class Meeting

**Final Presentations Code C**

- Thursday, May 1st, 2025 at 7:00 PM: Final Project Lightning Talks 

<!-- ## Week 1 - Setup

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|Tu Jan 14||||
|Th Jan 16|||[Reading: Gentle Chart Types](https://chartio.com/learn/charts/essential-chart-types-for-data-visualization/) </br> [Reading: Visualizations p. 19-32](https://ebookcentral.proquest.com/lib/allegheny-ebooks/reader.action?docID=427614) </br> [Lab 1: Hall of Fame](https://classroom.github.com/a/36z5eOtg) due 2:30pm Jan 26|

## Week 2 - Intro to Visualization in Sheets

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Jan 22|[Reading: Gentle Chart Types](https://chartio.com/learn/charts/essential-chart-types-for-data-visualization/) </br> [Reading: Visualizations p. 19-32](https://ebookcentral.proquest.com/lib/allegheny-ebooks/reader.action?docID=427614)|[Slides: Intro to Visualizations](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240122-introduction-to-visualizations.pdf) ||
|W Jan 24||[Slides: Organization and Transformation](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240124-data-transformation-organization.pdf) ||
|F Jan 26|Lightning talks 11-11:50am <br> [Lab 1: Hall of Fame](https://classroom.github.com/a/36z5eOtg) due 2:30pm||[Lab 2: Dot to dot](https://classroom.github.com/a/0Kb-l_iO) due Feb 2 at 2:30pm|

## Week 3 - Transformations

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Jan 29||[Slides: Tranformations Continued](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240129-transformations-continued.pdf)||
|W Jan 31||[Colab: Installation Instructions](https://colab.research.google.com/github/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240131_colab_intro.ipynb)||
|F Feb 02|||[Reading: File Naming](https://uq.pressbooks.pub/digital-essentials-data-and-files/chapter/file-naming-and-formats/) <br> [Reading: File Systems All Sections](https://e115.engr.ncsu.edu/file-systems/) <br> [Lab 3: Dot to do ipynb](https://classroom.github.com/a/igLOWZ-h) due Feb 9 at 2:30pm|

## Week 4 - Storytelling

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Feb 05||[Slides: File Organization](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240205-file-system-review.pdf)||
|W Feb 07|[Reading: File Naming](https://uq.pressbooks.pub/digital-essentials-data-and-files/chapter/file-naming-and-formats/) <br> [Reading: File Systems All Sections](https://e115.engr.ncsu.edu/file-systems/)|[Slides: Data Storytelling](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240207-data-storytelling.pdf)|[Reading: Storytelling Music Example p. 1-7](https://journals.sagepub.com/doi/epdf/10.2190/EM.31.1.c)|
|F Feb 09|[Lab 2: Dot to dot](https://classroom.github.com/a/0Kb-l_iO) due at 2:30pm <br> [Lab 3: Dot to dot ipynb](https://classroom.github.com/a/igLOWZ-h) due at 2:30pm|[Colab: Vocal Analysis](https://colab.research.google.com/github/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240209_voice_analysis.ipynb)|[Reading: Science & Story p. 8-14](https://allegheny.alma.exlibrisgroup.com/discovery/openurl?institution=01ACO_INST&rfr_id=info:sid%2Fsummon&rft_dat=ie%3D51154733620003906,ie%3D5159145450003906,ie%3D2148230190003906,language%3DEN&svc_dat=CTO&u.ignore_date_coverage=true&vid=01ACO_INST:Services) <br> [Lab 4: Voice Analysis](https://classroom.github.com/a/fJEPT6I4) due Feb 16th at 11:59pm|

## Week 5 - Google Analytics

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Feb 12|||[Reading: General Storytelling](https://clauswilke.com/dataviz/telling-a-story.html)|
|W Feb 14|[Reading: Storytelling Music Example p. 1-7](https://journals.sagepub.com/doi/epdf/10.2190/EM.31.1.c)|[Slides: Google Analytics by OBC](https://github.com/CMPSC-301-Allegheny-College-Spring-2023/classDocs/blob/main/lessons/02/02week_cs301_24Jan2023_googleAnalytics.pdf)|[Reading: Storytelling Business Example](https://mitsloan.mit.edu/ideas-made-to-matter/next-chapter-analytics-data-storytelling)|
|F Feb 16|[Lab 4: Voice Analysis](https://classroom.github.com/a/fJEPT6I4) due 11:59 pm||[Lab 5: Resto Google Analytics](https://classroom.github.com/a/RbaYQTOJ) due F Feb 23 at 11:59pm|

## Week 6 - Dashboards

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Feb 19||||
|W Feb 21||[Slides: Dashboards](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240221-dashboards.pdf)||
|F Feb 23|[Lab 5: Resto Google Analytics](https://classroom.github.com/a/RbaYQTOJ) due F Feb 23 at 11:59pm|||

## Week 7 - Introduction to Numpy

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Feb 26||||
|W Feb 28||Intro to numpy||
|F Mar 01||[Slides: transformations in numpy](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240301-transformations-in-numpy.pdf)|[Reading: Describing Data p. 17-46](https://ebookcentral.proquest.com/lib/allegheny-ebooks/reader.action?docID=1729064&ppg=31)|

## Spring Break

## Week 8 - Stats

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Mar 11|[Reading: Describing Data p. 17-46](https://ebookcentral.proquest.com/lib/allegheny-ebooks/reader.action?docID=1729064&ppg=31)|[Slides: data descriptors in numpy](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240311-describing-data-in-numpy.pdf)|[Lab 6: Data Descriptors in Numpy](https://classroom.github.com/a/yx1xFxym) due March 18th at 11am|
|W Mar 13|||[Reading: Preparing Data Tables p. 47-59](https://ebookcentral.proquest.com/lib/allegheny-ebooks/reader.action?docID=1729064&ppg=61)|
|F Mar 15||[Slides: distributions intro](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240315-distributions-intro.pdf)||

## Week 9 - Stats Continued

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Mar 18|[Lab 6: Data Descriptors in Numpy](https://classroom.github.com/a/yx1xFxym) due at 11am|[Slides: confidence interval, hypothesis testing](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240318-hypothesis-testing.pdf)||
|W Mar 20|[Reading: Preparing Data Tables p. 47-59](https://ebookcentral.proquest.com/lib/allegheny-ebooks/reader.action?docID=1729064&ppg=61)|[Slides: hypothesis testing continued](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240320-hypothesis-testing-continued.pdf)||
|F Mar 22||[Board: Matplotlib Intro]|[Lab 7: Testing Hypotheses](https://classroom.github.com/a/gnvNGjAL) due March 29th at 11:59pm|

## Week 10 - Matplotlib

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Mar 25||[Board: Logical Indexing]||
|W Mar 27||[Code: matplotlib formatting](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240327-matplotlib-formatting.py)||
|F Mar 29|[Lab 7: Testing Hypotheses](https://classroom.github.com/a/gnvNGjAL) due March at 11:59pm||[Lab 8: Matplotlib](https://classroom.github.com/a/UlUzGaDt) due April 5 at 11:59pm|

## Week 11 - Linear Relationships

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Apr 01||[Slides: Correlation and Regression](https://github.com/allegheny-college-cmpsc-105-spring-2024/course-materials/blob/main/notes/20240401-correlation-regression.pdf)|[Reading: Correlation p. 69-71](https://ebookcentral.proquest.com/lib/allegheny-ebooks/reader.action?docID=1729064&ppg=83)|
|W Apr 03||||
|F Apr 05|[Lab 8: Matplotlib](https://classroom.github.com/a/UlUzGaDt) due at 11:59pm|||

## Week 12 - Tableau Public

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Apr 08||[Biased and Unbiased Slopes]||
|W Apr 10||Tableau Public - first exploration||
|F Apr 12||Tableau Public - overfitting |[Lab 9: Songdata Correlations](https://classroom.github.com/a/VfrKh8M7) due Apr 19 at 11:59pm|

## Week 13 - Project Consultation

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Apr 15||||
|W Apr 17||||
|F Apr 19|[Lab 9: Songdata Correlations](https://classroom.github.com/a/VfrKh8M7) due at 11:59pm|[Initial Project Meetings](https://docs.google.com/spreadsheets/d/1PQoFkdfPZGWLfPZzknpVNqdnq6-bgphOttl5uiCnWKU/edit?usp=sharing)||

## Week 14 - Project Consultation

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Apr 22||||
|W Apr 24|||[Project Repo: Data Insight](https://classroom.github.com/a/pojZiZlA) due May 7 at 11:59am|
|F Apr 26 class||[Department Survey](https://forms.gle/KhXfL4juCt7VPegRA) <br> [RSE Survey](https://allegheny.instructure.com/courses/10873/external_tools/1268)||
|F Apr 26 lab|[Checkpoint Presentations](https://docs.google.com/spreadsheets/d/1PQoFkdfPZGWLfPZzknpVNqdnq6-bgphOttl5uiCnWKU/edit?usp=sharing)|||

## Week 15 - Project Consultation

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|M Apr 29|[Checkpoint Presentations](https://docs.google.com/spreadsheets/d/1PQoFkdfPZGWLfPZzknpVNqdnq6-bgphOttl5uiCnWKU/edit?usp=sharing)|||

## Final Project Due

| Date  | Due              | Links to in-class materials | Links to new assignments |
|-------|------------------|-----------------------------|----------------------|
|Tu May 07|[Project Repo: Data Insight](https://classroom.github.com/a/pojZiZlA) due at 11:59am||| -->
